#!/bin/bash

MAIN_GITHUB_FOLDER_PATH=$1
if [ "$MAIN_GITHUB_FOLDER_PATH" == "" ]; then
    MAIN_GITHUB_FOLDER_PATH=~/github
fi

cd $MAIN_GITHUB_FOLDER_PATH

for d in */ ; do
    path=$MAIN_GITHUB_FOLDER_PATH/$d
    cd $path

    echo -e "\n\n----------------------------------------------------------------\n"
    echo -e "Proj: "$d
    echo -e "Path: $path\n"
    git fetch
    echo -e "\n----------------------------------------------------------------\n\n"
done